{{- if and (not .Values.secrets.copilotCli.existingSecret) .Values.secrets.copilotCli.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eks-upgrade-advisor.copilotSecretName" . }}
  labels:
    {{- include "eks-upgrade-advisor.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.copilotCli.existingSecretKey }}: {{ .Values.secrets.copilotCli.token | b64enc | quote }}
{{- end }}
